use_squash_merge = true
cut_body_after = "_ _ _"
pr_status = [
# This must be un-commented once Bors merges the PR that new CI check
#  "Validate conventional PR title",
]
status = [
  "Check Rust formatting",
  "Clippy correctness checks (%)",
  "Build Docs",
]
