[package]
name = "jumpy"
version = "0.4.3"
description = "A tactical 2D shooter"
authors = ["The Fish Fight Game & Spicy Lobster Developers"]
license = "MIT OR Apache-2.0"
edition = "2021"
default-run = "jumpy"

[workspace]
resolver = "2"
members = [
    ".",
    "crates/bevy-has-load-progress",
    "crates/bevy-has-load-progress/macros",
]

[dependencies.bevy]
version = "0.8"
default-features = false
features = [
    "x11",
    "png",
    "filesystem_watcher",
    "bevy_gilrs"
]

[dependencies]
anyhow = "1.0.58"
bevy-parallax = "0.2.0"
bevy_egui = "0.16.1"
egui_extras = "0.19.0"
bevy_kira_audio = { version = "0.12.0", features = ["mp3"] }
iyes_loopless = "0.7.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.9.2"
thiserror = "1.0.31"
structopt = "0.3.26"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
bevy-has-load-progress = { path = "crates/bevy-has-load-progress", features = ["bevy_egui"] }
leafwing-input-manager = { version = "0.5.2", default-features = false }
unic-langid = "0.9.0"
bevy_fluent = "0.4.0"
sys-locale = "0.2.1"
fluent = "0.16.0"
directories = "4.0.1"
async-channel = "1.6.1"
once_cell = "1.13.0"
bevy_mod_js_scripting = { git = "https://github.com/zicklag/bevy_mod_js_scripting.git", branch = "jumpy" }
bevy_ecs_tilemap = { version = "0.7.0", features = ["atlas"] }
bevy_prototype_lyon = "0.6.0"
fnv = "1.0.7"
base64 = "0.13.0"
bevy_renet = { git = "https://github.com/zicklag/renet.git", branch = "jumpy" }
postcard = { version = "1.0.2", default-features = false, features = ["alloc"] }

# Debug tools
bevy-inspector-egui = { version = "0.13.0" }
ulid = { version = "1.0.0", features = ["serde"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3", features = ["Window","Location","Storage"] } 

[profile.dev.package."*"]
opt-level = 1 # Set this to 3 if the game becomes slow to respond during gameplay
debug = false

[profile.release]
lto = true
codegen-units = 1 # Improved rapier physics perf, so it might help other stuff, too

[patch.crates-io]
renet = { git = "https://github.com/zicklag/renet.git", branch = "jumpy" }
