[package]
name = "jumpy"
version = "0.4.3"
description = "A tactical 2D shooter"
authors = ["The Fish Fight Game & Spicy Lobster Developers"]
license = "MIT OR Apache-2.0"
edition = "2021"
default-run = "jumpy"

[workspace]
resolver = "2"
members = [
    ".",
    "crates/*"
]

[features]
default = ["render"]
render = [
    "bevy/x11",
    "bevy/png",
    "bevy/filesystem_watcher",
    "bevy/bevy_gilrs",
]

[dependencies]
anyhow = "1.0.58"
async-channel = "1.7.1"
base64 = "0.13.0"
bevy-has-load-progress = { path = "crates/bevy-has-load-progress", features = ["bevy_egui"] }
bevy-inspector-egui = { version = "0.13.0" }
bevy-parallax = "0.2.0"
bevy_ecs_dynamic = { git = "https://github.com/jakobhellermann/bevy_ecs_dynamic" }
bevy_ecs_tilemap = { version = "0.8.0", features = ["atlas"] }
bevy_egui = "0.16.1"
bevy_fluent = "0.4.0"
bevy_ggrs = "0.10.0"
bevy_kira_audio = { version = "0.12.0", features = ["mp3"] }
bevy_mod_js_scripting = { git = "https://github.com/zicklag/bevy_mod_js_scripting.git", branch = "jumpy" }
bevy_prototype_lyon = "0.6.0"
bevy_tweening = { version = "0.5", default-features = false }
blocking = "1.2.0"
bytes = "1.2.1"
clap = { version = "4.0.18", features = ["derive", "env"] }
directories = "4.0.1"
egui_extras = "0.19.0"
either = "1.8.0"
fluent = "0.16.0"
fnv = "1.0.7"
futures-lite = "1.12.0"
getrandom = { version = "0.2", features = ["js"] }
ggrs = "0.9.2"
iyes_loopless = "0.8.0"
jumpy-matchmaker-proto = { path = "crates/matchmaker-proto" }
leafwing-input-manager = { version = "0.6.1", default-features = false }
normalize-path = "0.2.0"
once_cell = "1.13.0"
postcard = { git = "https://github.com/zicklag/postcard.git", branch = "custom-error-messages", default-features = false, features = ["alloc", "use-std"] }
rand = "0.8.5"
rustls = { version = "0.20.7", features = ["dangerous_configuration", "quic"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.9.2"
sys-locale = "0.2.1"
thiserror = "1.0.31"
unic-langid = "0.9.0"
bytemuck = "1.12.3"
bitfield = "0.14.0"
numquant = "0.2.0"

[dependencies.bevy]
version = "0.8"
default-features = false
features = [
    "x11",
    "png",
    "filesystem_watcher",
    "bevy_gilrs"
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3", features = ["Window","Location","Storage"] } 

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
quinn = { version = "0.9", default-features = false, features = ["futures-io", "native-certs", "tls-rustls"] }
quinn-bevy = { path = "crates/quinn-bevy" }

[profile.dev.package."*"]
opt-level = 1 # Set this to 3 if the game becomes slow to respond during gameplay
debug = false

[profile.release]
lto = true
codegen-units = 1 # Improved rapier physics perf, so it might help other stuff, too
