[package]
name = "jumpy"
version = "0.5.1"
description = "A tactical 2D shooter"
authors = ["The Fish Fight Game & Spicy Lobster Developers"]
license = "MIT OR Apache-2.0"
edition = "2021"
default-run = "jumpy"

[features]
default = ["render"]
render = [
    "bevy/x11",
    "bevy/png",
    "bevy/filesystem_watcher",
    "bevy/bevy_gilrs",
]

[dependencies]
anyhow = "1.0.58"
async-channel = "1.7.1"
base64 = "0.13.0"
bevy-inspector-egui = { version = "0.13.0" }
bevy-parallax = "0.2.0"
bevy_ecs_dynamic = { git = "https://github.com/jakobhellermann/bevy_ecs_dynamic", rev = "aa7a051a49bd134cfd8c169542e16526bf2b36b3" }
bevy_ecs_tilemap = { version = "0.7.0", features = ["atlas"] }
bevy_egui = "0.16.1"
bevy_fluent = "0.4.0"
bevy_framepace = "0.7"
bevy_ggrs = { git = "https://github.com/zicklag/bevy_ggrs.git", branch = "jumpy" }
bevy_kira_audio = { version = "0.12.0", features = ["ogg"], default-features = false }
# bevy_mod_js_scripting = { git = "https://github.com/zicklag/bevy_mod_js_scripting.git", branch = "jumpy" }
bevy_prototype_lyon = "0.6.0"
bevy_system_graph = "0.3.0"
bevy_tweening = { version = "0.5", default-features = false }
bitfield = "0.14.0"
blocking = "1.2.0"
bones_has_load_progress = { git = "https://github.com/fishfolk/bones.git", features = ["bevy_egui"] }
bones_matchmaker_proto = { git = "https://github.com/fishfolk/bones.git" }
bones_camera_shake = { git = "https://github.com/DRuppFv/bones", branch = "camera_shake_bevy0.8" }
bytemuck = "1.12.3"
bytes = "1.2.1"
clap = { version = "4.0.18", features = ["derive", "env"] }
directories = "4.0.1"
egui_extras = "0.19.0"
either = "1.8.0"
fluent = "0.16.0"
fnv = "1.0.7"
futures-lite = "1.12.0"
getrandom = { version = "0.2", features = ["js"] }
iyes_loopless = "0.8.0"
leafwing-input-manager = { version = "0.6.1", default-features = false }
log = { version = "0.4.17", features = ["release_max_level_debug"] }
mimalloc = { version = "0.1.32", default-features = false }
normalize-path = "0.2.0"
numquant = "0.2.0"
once_cell = "1.13.0"
postcard = { version = "1.0.2", default-features = false, features = ["alloc", "use-std"] }
rand = "0.8.5"
rustls = { version = "0.20.7", features = ["dangerous_configuration", "quic"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.2"
sys-locale = "0.2.1"
thiserror = "1.0.31"
tracing = { version = "0.1.37", features = ["release_max_level_debug"] }
turborand = { version = "0.8.0", features = ["atomic", "serialize"] }
unic-langid = "0.9.0"

[dependencies.bevy]
version = "0.8"
default-features = false
features = [
    "x11",
    "png",
    "filesystem_watcher",
    "bevy_gilrs"
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3", features = ["Window","Location","Storage"] } 

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
quinn = { version = "0.9", default-features = false, features = ["futures-io", "native-certs", "tls-rustls"] }
quinn_runtime_bevy = { git = "https://github.com/fishfolk/bones.git" }

[profile.dev.package."*"]
opt-level = 3 # Set this to 3 if the game becomes slow to respond during gameplay
debug = true

[profile.release]
lto = true
codegen-units = 1 # Improved rapier physics perf, so it might help other stuff, too

[patch.crates-io]
# Fix for https://github.com/bevyengine/bevy/issues/6790
bevy_hierarchy = { git = "https://github.com/zicklag/bevy.git", branch = "dont-error-on-non-mapped-children-entities" }
